from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUT = ROOT / "dist" / "codingame_bot.py"


def strip_module_imports(content: str) -> str:
    cleaned_lines: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped == "from __future__ import annotations":
            continue
        if stripped.startswith("from game_state import"):
            continue
        if stripped.startswith("from strategy import"):
            continue
        cleaned_lines.append(line)
    return "\n".join(cleaned_lines).strip() + "\n"


def main() -> None:
    game_state = strip_module_imports((SRC / "game_state.py").read_text(encoding="utf-8"))
    strategy = strip_module_imports((SRC / "strategy.py").read_text(encoding="utf-8"))
    main_src = strip_module_imports((SRC / "main.py").read_text(encoding="utf-8"))

    OUT.parent.mkdir(parents=True, exist_ok=True)

    generated = (
        "# Auto-generated by scripts/build_single_file.py\n"
        "# Source of truth remains in src/.\n\n" + game_state + "\n" + strategy + "\n" + main_src
    )

    OUT.write_text(generated, encoding="utf-8")
    print(f"Generated: {OUT}")


if __name__ == "__main__":
    main()
